### ISSUE TITLE
позиціонування

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/User-card#3]
https://github.com/VasylUlianovskyi/User-card/blob/e38a8372bd3ca01b77fdcbb22995ca6b90cf9bde/assest/css/style.css#L84
https://github.com/VasylUlianovskyi/User-card/blob/e38a8372bd3ca01b77fdcbb22995ca6b90cf9bde/assest/css/style.css#L106
https://github.com/VasylUlianovskyi/User-card/blob/e38a8372bd3ca01b77fdcbb22995ca6b90cf9bde/assest/css/style.css#L113
- позиціонування бажано використовувати тільки тоді, якщо без нього не обійтися,оскільки воно ламає стандартну поведінку елементів (розміщення в нормальному потоці). Крім того, саме `relative` небезпечне тим, що на його місці лишиться порожнє місце. Тут можна використати від'ємний марджин для фото, і тоді всі написи під ним автоматом поповзуть вгору.

**Comment by VasylUlianovskyi** [comment]
++
